/**
 * 100 MEDIUM-complexity app ideas for Vibetree Pro builds, organized by technology.
 * Each is a step up from the basic version in APP_IDEAS_BY_CATEGORY:
 *   - Multiple screens with NavigationStack
 *   - Richer data models (Codable structs, enums)
 *   - CRUD + search/filter
 *   - Tabs, sheets, custom views
 *   - More polished UI (animations, empty states, icons)
 *
 * Used by APP_IDEAS_MEDIUM/*.md (see scripts/generate-app-ideas-medium.mjs).
 */
export type AppIdea = { title: string; prompt: string };

export const APP_IDEAS_MEDIUM_BY_CATEGORY: Record<string, AppIdea[]> = {
  "WebKit & in-app browser": [
    { title: "Quick links + WKWebView", prompt: "Build a quick links app with NavigationStack. Main screen: searchable list of saved links grouped by category (e.g. Social, News, Work). Tap opens a detail screen with WKWebView (UIViewRepresentable) loading that URL, plus a share button and a favorite toggle. Add/edit link form with title, URL, and category picker. Persist with Codable + UserDefaults. Include pull-to-refresh and swipe-to-delete." },
    { title: "Read-later + in-app browser", prompt: "Build a read-later app with tabs. Tab 1: list of saved articles (title, URL, date added) with search bar and swipe actions (delete, mark as read). Tab 2: reading list filtered to unread only. Tapping opens WKWebView with a toolbar (back, forward, share, mark read). Add article sheet with URL field and optional title. Persist with Codable + UserDefaults. Show unread badge count on tab." },
    { title: "Bookmarks list", prompt: "Build a bookmarks manager with folders. Main screen: list of folders; tap folder to see bookmarks inside. Each bookmark has title, URL, and optional note. Add/edit bookmark sheet with folder picker. Swipe to move between folders. Search across all bookmarks. Long-press to copy URL. Persist folder tree with Codable + UserDefaults. Empty state when no bookmarks." },
    { title: "Link-in-bio", prompt: "Build a link-in-bio page editor. Screen 1: preview of your bio page (profile image placeholder, display name, bio text, vertical list of link buttons). Screen 2: edit mode — reorder links with drag, add/edit/delete links (title, URL, icon name from SF Symbols). Links open in SFSafariViewController. Persist with Codable + UserDefaults. Share button exports profile as text." },
    { title: "Open URL in Safari", prompt: "Build a URL launcher with history. Main screen: text field for URL, Open button that launches in Safari, and a history list of previously opened URLs with timestamps. Tap history item to re-open. Swipe to delete history entries. Validate URL format before opening. Persist history with Codable + UserDefaults. Show empty state when no history." },
    { title: "In-app Safari / WKWebView", prompt: "Build a mini browser. Main screen: URL bar at top, WKWebView below, toolbar at bottom with back, forward, refresh, and share buttons. Bookmarks sheet: list of saved bookmarks; tap to load. Add current page to bookmarks button. Persist bookmarks with Codable + UserDefaults. Show loading progress bar while page loads." },
  ],
  "Persistence (UserDefaults)": [
    { title: "Daily quote or goal", prompt: "Build a daily focus app with history. Main screen: today's focus quote in large typography with an edit button. Below: scrollable list of past 30 days' quotes with dates. Add/edit sheet with text field and date. Settings screen: toggle daily reminder notification, choose text color theme. Persist all entries with Codable + UserDefaults. Empty state for first launch." },
    { title: "Simple counter", prompt: "Build a multi-counter app. Main screen: list of named counters, each showing current value. Tap a counter to open detail screen with large number display, +/- buttons, step size picker (1, 5, 10), and reset button with confirmation. Add counter sheet with name and starting value. Swipe to delete. Persist all counters with Codable + UserDefaults." },
    { title: "Todo list", prompt: "Build a todo app with categories. Main screen: segmented control to filter (All, Active, Completed). List of tasks with checkboxes, due dates, and priority colors (high=red, medium=orange, low=green). Add task sheet: title, due date picker, priority picker, optional notes. Swipe to delete. Sort by due date or priority. Persist with Codable + UserDefaults. Show completion percentage at top." },
    { title: "Shopping list", prompt: "Build a shopping list app with categories. Main screen: sectioned list grouped by aisle (Produce, Dairy, etc.). Each item has name, quantity, and checkbox. Add item sheet with name, quantity stepper, and category picker. Swipe to delete. Button to clear all checked items with confirmation. Show total items and checked count. Persist with Codable + UserDefaults." },
    { title: "Mood tracker", prompt: "Build a mood tracker with charts. Main screen: today's mood picker (5 emoji options with labels), optional note field. Below: scrollable calendar-style grid showing mood emoji for each day of the current month. Detail screen when tapping a day: mood, note, date. Stats tab: most common mood, current streak. Persist with Codable + UserDefaults." },
    { title: "Notes app", prompt: "Build a notes app with folders and search. Main screen: list of folders (Personal, Work, Ideas). Tap folder to see notes list with title and preview text. Note editor: title field and multi-line text editor with character count. Search bar searches across all folders. Swipe to delete or move to different folder. Sort by date modified. Persist with Codable + UserDefaults." },
    { title: "Gratitude list", prompt: "Build a gratitude journal with streaks. Main screen: today's entry — 3 text fields for things you're grateful for, with Save. Below: calendar view showing which days have entries (green dot). Streak counter at top (consecutive days). History screen: scrollable list of past entries by date. Persist with Codable + UserDefaults. Encouraging empty state for first launch." },
    { title: "Habit checklist", prompt: "Build a habit tracker with weekly view. Main screen: list of habits with daily checkboxes for the current week (Mon–Sun columns). Add/edit habit sheet: name, icon picker (SF Symbols), target days per week. Tap habit row to see detail: completion rate percentage, streak count, and a month grid. Swipe to delete habit. Persist with Codable + UserDefaults." },
    { title: "Minimal expense log", prompt: "Build an expense tracker with categories. Main screen: list of expenses (amount, label, category icon, date) with running total at top. Add expense sheet: amount field, label, category picker (Food, Transport, Entertainment, etc.), date picker. Filter by category using segmented control. Monthly summary view showing total per category. Persist with Codable + UserDefaults." },
    { title: "Water intake tracker", prompt: "Build a water intake app with progress ring. Main screen: animated circular progress ring showing glasses vs daily goal. Quick-add buttons (+1 glass, +½ glass, custom amount). Below: timeline of today's intake entries with timestamps. Settings sheet: daily goal stepper, glass size selector. History tab: bar chart placeholder showing last 7 days. Persist with Codable + UserDefaults." },
    { title: "Sleep log", prompt: "Build a sleep tracker with trends. Main screen: log tonight's sleep — bedtime picker, wake time picker, quality rating (1–5 stars), Save. Below: list of last 14 nights showing hours and quality. Stats view: average sleep time, average quality, best/worst night. Color-code entries (green for 7+ hrs, yellow for 5–7, red for <5). Persist with Codable + UserDefaults." },
    { title: "Focus word", prompt: "Build a focus word app with history and widget-style display. Main screen: current focus word displayed large with a motivational background gradient. Edit sheet to change word. Below: scrollable list of past focus words with dates. Settings: choose from 4 gradient color themes. Tap word to copy to clipboard. Persist with Codable + UserDefaults. Animated transition when changing word." },
    { title: "Rating tracker", prompt: "Build a rating tracker with categories. Main screen: list of rated items grouped by category (Movies, Books, Restaurants). Each shows name and 1–5 star rating. Add item sheet: name, category picker, star rating selector, optional notes. Detail screen: full info with edit capability. Sort by rating or date. Filter by category. Average rating per category shown in section headers. Persist with Codable + UserDefaults." },
    { title: "Quick contacts", prompt: "Build a contacts app with groups. Main screen: alphabetically sectioned list of contacts (name, phone, email). Tap for detail screen showing all info with call/email action buttons (show alert). Add/edit contact sheet with validation (require name). Groups tab: create groups and assign contacts. Search bar. Swipe to delete. Persist with Codable + UserDefaults." },
    { title: "Recipe card", prompt: "Build a recipe book app. Main screen: grid of recipe cards with title and cook time. Tap for detail: title, servings stepper (adjusts ingredient quantities), ingredients list, and step-by-step instructions. Add/edit recipe sheet: title, servings, ingredients (add/remove rows), instructions (add/remove steps), cook time. Search recipes. Persist with Codable + UserDefaults." },
    { title: "Packing list", prompt: "Build a packing list app with templates. Main screen: list of trips (name, date, progress). Tap trip for sectioned checklist (Clothes, Toiletries, Electronics, Documents). Add item to section. Check/uncheck items. Progress bar showing packed percentage. New trip sheet with name, date, and template picker (Weekend, Business, Beach). Persist with Codable + UserDefaults." },
    { title: "Wishlist", prompt: "Build a wishlist app with priorities. Main screen: list of items with name, estimated price, and priority tag (Must Have, Nice to Have, Dream). Add/edit sheet: name, price, URL (optional), priority picker, notes. Sort by price or priority. Total estimated cost at top. Swipe to mark as purchased (moves to Purchased tab). Two tabs: Active and Purchased. Persist with Codable + UserDefaults." },
    { title: "3-goals app", prompt: "Build a goals app with progress tracking. Main screen: 3 active goal cards, each with title, target date, progress slider (0–100%), and status color. Tap card for detail: description, milestones checklist, date created, days remaining. Edit goal sheet. Archive completed goals to a history list. Motivational quote at bottom. Persist with Codable + UserDefaults." },
    { title: "One-line journal", prompt: "Build a one-line-a-day journal with calendar. Main screen: today's entry field with mood emoji picker and Save. Calendar view (month grid) with dots on days that have entries. Tap a day to read/edit that entry. Stats: total entries, longest streak, most used mood. Export all entries as text (share sheet). Persist with Codable + UserDefaults." },
    { title: "Single-metric tracker", prompt: "Build a multi-metric dashboard. Main screen: list of tracked metrics (e.g. Weight, Steps, Pages Read), each showing current value and trend arrow (up/down). Tap metric for detail: history list, min/max/average stats, and a simple line chart placeholder. Add metric sheet: name, unit, and starting value. Log new value with date. Persist with Codable + UserDefaults." },
    { title: "Quick notes", prompt: "Build a quick notes app with tags. Main screen: list of notes with title preview and colored tag dots. Add note sheet: text field and tag picker (Important, Idea, Reminder — each with a color). Filter by tag using horizontal scroll chips. Search bar. Swipe to delete or pin. Pinned notes appear at top. Timestamp on each note. Persist with Codable + UserDefaults." },
    { title: "Minimal profile", prompt: "Build a profile editor with photo placeholder. Main screen: profile card (circular image placeholder, name, email, bio). Edit mode: editable fields with validation (email format). Settings screen: toggle dark mode, choose accent color from 4 options. About screen: app version and credits. Tab bar with Profile and Settings. Persist with Codable + UserDefaults." },
    { title: "Settings toggles", prompt: "Build a settings app with sections. Main screen: grouped form with sections — Appearance (dark mode toggle, accent color picker), Notifications (toggle, time picker for daily reminder), Privacy (toggle analytics, clear data button with confirmation). About section: version, rate app button, contact support button. Reset all settings button. Persist all with UserDefaults." },
    { title: "Swipe-to-delete list", prompt: "Build an editable list with multiple actions. Main screen: list of items with swipe-left to delete (with confirmation) and swipe-right to favorite. Favorites section at top. Add item sheet with name and optional emoji icon. Reorder items with drag handles (EditButton). Undo last delete with toast. Show item count in navigation title. Persist with Codable + UserDefaults." },
  ],
  "Timers & time": [
    { title: "Countdown timer", prompt: "Build a countdown timer app with presets. Main screen: large countdown display with circular progress ring. Preset buttons (1 min, 5 min, 10 min, custom). Start/Pause/Reset controls. When timer ends: play sound, show alert, optional vibration. History tab: list of completed timers with duration and date. Settings: choose alarm sound. Persist presets and history with Codable + UserDefaults." },
    { title: "Stopwatch", prompt: "Build a stopwatch app with laps and comparison. Main screen: large elapsed time display (mm:ss.xx), Start/Stop/Reset buttons, Lap button. Lap list below showing lap number, lap time, and total time. Highlight fastest lap (green) and slowest lap (red). Share results button (share sheet with formatted text). Persist last session's laps with Codable + UserDefaults." },
    { title: "Countdown to date", prompt: "Build a multi-event countdown app. Main screen: list of upcoming events sorted by date, each showing event name, date, and days/hours remaining with a progress bar. Add event sheet: name, date picker, icon picker (SF Symbols), color picker. Past events move to Archive tab. Detail screen: full countdown (days, hours, minutes, seconds updating live). Persist with Codable + UserDefaults." },
    { title: "Big clock", prompt: "Build a customizable clock app with world clocks. Main screen: large digital clock with date, updating every second. Settings: choose from 4 font styles, 4 color themes, toggle 12/24 hour, toggle seconds. World clocks tab: list of added time zones showing current time. Add time zone from searchable list. Persist preferences and zones with UserDefaults." },
    { title: "Pomodoro timer", prompt: "Build a Pomodoro timer with session tracking. Main screen: circular timer with work/break phases. Configurable: work duration (15–60 min), short break (3–10 min), long break (15–30 min), sessions before long break. Start/Pause/Skip controls. Session counter (e.g. 3/4). Today's stats: completed pomodoros, total focus time. History tab: daily summaries for past 7 days. Persist with Codable + UserDefaults." },
    { title: "Lap timer", prompt: "Build a multi-athlete lap timer. Main screen: list of athletes/lanes (add/remove). Tap an athlete to record a lap — shows lap times in a sub-list. Global start/stop that starts all timers simultaneously. Summary view: table comparing athletes' lap times side by side, with fastest lap highlighted. Reset all button with confirmation. Persist with Codable + UserDefaults." },
  ],
  "Lists & navigation": [
    { title: "Filterable list", prompt: "Build a filterable and sortable list. Main screen: search bar, sort button (A–Z, Z–A, newest, oldest), and filter chips (categories). List of 20 items with title, subtitle, category tag, and date. Tap for detail screen with full info. Add item sheet with all fields. Empty state when filter matches nothing. Animate list changes. Persist with Codable + UserDefaults." },
    { title: "Segmented content", prompt: "Build a segmented content app with 3 sections. Main screen: segmented control (Feed, Popular, Saved). Feed: chronological list of cards. Popular: same items sorted by likes count. Saved: only items marked as saved. Each card has title, preview text, like button with count, and save button. Tap card for detail screen. Animated segment transitions. Persist saved items with Codable + UserDefaults." },
    { title: "Tab bar app", prompt: "Build a 3-tab app with proper navigation. Tab 1 (Home): dashboard with summary cards. Tab 2 (Browse): searchable list with NavigationStack to detail screens. Tab 3 (Profile): profile view with settings. Badge on Browse tab showing item count. Proper back navigation within each tab. Consistent styling across tabs. Persist minimal state with UserDefaults." },
    { title: "Sectioned list", prompt: "Build a sectioned contact directory. Main screen: alphabetically sectioned list with section index (A–Z sidebar). Each row shows avatar initial, name, and role. Tap for detail screen: full info with action buttons. Search bar that searches across all sections. Add person sheet with name, role, and email. Section headers show count. Persist with Codable + UserDefaults." },
    { title: "Card list", prompt: "Build a card-based content browser. Main screen: vertical list of cards with image placeholder, title, subtitle, and category tag. Toggle between list and 2-column grid views. Tap card for detail screen with hero image area, title, full description, and related cards section. Floating action button to add new card. Search bar. Persist with Codable + UserDefaults." },
    { title: "List-to-detail (NavigationStack)", prompt: "Build a product catalog with NavigationStack. Main screen: list of products with image placeholder, name, price, and rating stars. Tap for detail: large image area, name, price, description, rating, and Add to Favorites button. Favorites screen accessible from toolbar. Search and filter by price range. Sort by price or rating. Persist favorites with Codable + UserDefaults." },
    { title: "Grid layout", prompt: "Build a photo grid gallery. Main screen: 3-column grid of image placeholder cards with title overlays. Tap for full-screen detail with title, description, and date. Toolbar toggle between 2-column and 3-column grid. Add item sheet with title and description. Long-press for context menu (delete, share, favorite). Section headers by month. Persist with Codable + UserDefaults." },
    { title: "Horizontal scroll", prompt: "Build a media browser with horizontal carousels. Main screen: multiple horizontal scroll sections (Featured, Recent, Categories). Featured: large paging cards. Recent: medium cards. Categories: small icon+label cards. Tap any card for detail screen. Section headers with See All button (navigates to full list). Pull-to-refresh. Animated scroll snapping on Featured." },
    { title: "Pull-to-refresh", prompt: "Build a feed app with pull-to-refresh. Main screen: list of posts (author, text, timestamp, like count). Pull to refresh adds new mock posts at top with animation. Like button toggles with count. Tap post for detail with comments section (mock data). Floating compose button opens new post sheet. Show relative timestamps (2m ago, 1h ago). Persist posts with Codable + UserDefaults." },
    { title: "Long-press context menu", prompt: "Build a file manager with context menus. Main screen: list of files/folders with icons, names, sizes, and dates. Long-press shows context menu: Rename, Move, Duplicate, Delete, Share. Tap folder to navigate into it (NavigationStack). Breadcrumb path shown in nav title. Add file/folder buttons. Sort by name, size, or date. Swipe to delete. Persist with Codable + UserDefaults." },
    { title: "Placeholder list with SF Symbols", prompt: "Build a services dashboard with SF Symbol icons. Main screen: grouped list with sections (Account, Activity, Settings). Each row has colored SF Symbol icon, title, subtitle, and chevron. Tap for detail screen specific to that item. Some rows show badge counts. Toggle between list view and icon grid view. Search across all items. Header with user greeting and date." },
  ],
  "Forms & pickers": [
    { title: "Feedback form", prompt: "Build a feedback form with validation and history. Main screen: multi-step form — Step 1: name and email (validated). Step 2: category picker (Bug, Feature, Other) and message text editor. Step 3: rating (1–5 stars) and optional screenshot placeholder. Submit shows success screen with animation. Feedback history tab: list of past submissions. Persist with Codable + UserDefaults." },
    { title: "Simple form", prompt: "Build a registration form with validation. Main screen: form with name, email, phone, password, and confirm password fields. Real-time validation: red border and error message for invalid fields. Email format check, password strength indicator (weak/medium/strong), passwords match check. Submit button disabled until all valid. Success screen. Clear form button. Persist last submission with UserDefaults." },
    { title: "Picker", prompt: "Build a preferences editor with multiple pickers. Main screen: form with wheel picker (favorite color), menu picker (language), inline picker (country), and segmented picker (theme: light/dark/system). Preview section at bottom showing all selected values. Save and Reset buttons. Animate changes. Persist all preferences with UserDefaults." },
    { title: "Slider", prompt: "Build a settings configurator with sliders. Main screen: multiple sliders — font size (12–32, live preview text below), opacity (0–100%, preview rectangle), speed (1x–3x), and volume. Each slider shows current value label. Reset to Defaults button. Before/After toggle to compare. Persist all values with UserDefaults. Haptic feedback on slider snap points." },
    { title: "Toggle list", prompt: "Build a feature flags manager. Main screen: sectioned list of feature toggles grouped by category (UI, Performance, Experimental). Each toggle has title, description, and status indicator. Some toggles have dependencies (enabling A auto-enables B). Warning sheet when disabling critical features. Search toggles. Export current config (share sheet). Persist all with UserDefaults." },
    { title: "Stepper", prompt: "Build an order customizer with steppers. Main screen: list of menu items, each with name, base price, and quantity stepper (0–10). Customization sheet per item: size picker (S/M/L with price modifier) and add-on toggles. Running total at bottom with item count badge. Clear order button with confirmation. Order summary screen with itemized list. Persist last order with Codable + UserDefaults." },
    { title: "Date picker", prompt: "Build an event planner with date pickers. Main screen: list of upcoming events sorted by date. Add event sheet: title, start date picker, end date picker (must be after start), all-day toggle, repeat picker (None, Daily, Weekly, Monthly). Calendar view showing events as dots on dates. Tap date to see events for that day. Validate no overlapping events. Persist with Codable + UserDefaults." },
    { title: "Time picker", prompt: "Build a daily schedule builder. Main screen: timeline view (6 AM – 10 PM) with time blocks. Add block sheet: title, start time picker, end time picker, color picker. Blocks display on the timeline with their color. Detect and warn about overlapping blocks. Edit block by tapping. Delete with swipe. Total scheduled hours counter. Persist with Codable + UserDefaults." },
  ],
  "Calculators & tools": [
    { title: "Color picker", prompt: "Build a color palette tool. Main screen: large color preview area with three slider groups (RGB and HSB toggle). Below: hex code (tap to copy), RGB values, and HSB values. Save color to palette button. Palettes tab: grid of saved colors, tap to load, long-press to delete. Generate complementary and analogous colors. Share palette as text. Persist palettes with Codable + UserDefaults." },
    { title: "Dice roller", prompt: "Build a dice roller with customization. Main screen: visual dice display area showing 1–6 dice with pip faces. Controls: dice count stepper (1–6), dice type picker (d4, d6, d8, d10, d12, d20). Roll button with shake animation. Show total and individual results. History list of past 20 rolls. Stats: average roll, highest, lowest. Shake-to-roll gesture. Persist history with Codable + UserDefaults." },
    { title: "Random number", prompt: "Build a random number generator with distributions. Main screen: large result display with generate button. Settings: min/max fields, count of numbers to generate (1–10), unique toggle (no repeats), sort toggle. History tab: list of past generations with parameters. Favorites: save useful sets. Copy results to clipboard. Animated number reveal. Persist history and favorites with Codable + UserDefaults." },
    { title: "Tip calculator", prompt: "Build a tip calculator with bill splitting. Main screen: bill amount field, tip percentage slider (0–30% with presets: 15%, 18%, 20%), split stepper (1–12 people). Results: tip amount, total, per-person amount. Round up/down buttons for per-person. Tax toggle with rate field. History tab: past calculations with date and restaurant name. Share bill summary. Persist history with Codable + UserDefaults." },
    { title: "Unit converter", prompt: "Build a multi-category unit converter. Main screen: category picker (Length, Weight, Temperature, Volume, Speed). Two unit pickers and two input fields (bidirectional conversion). Swap units button with animation. Favorites tab: save frequent conversions. History of recent conversions. Support at least 5 units per category. Copy result button. Persist favorites and history with Codable + UserDefaults." },
    { title: "BMI calculator", prompt: "Build a BMI tracker with history. Main screen: height input (toggle ft/in or cm), weight input (toggle lbs or kg), Calculate button. Result: BMI value, category with color (Underweight/Normal/Overweight/Obese), healthy weight range. History tab: list of past entries with date and BMI, simple trend indicator (arrow up/down). Goal weight field. Chart placeholder showing BMI over time. Persist with Codable + UserDefaults." },
    { title: "Random name picker", prompt: "Build a random picker with groups. Main screen: multiple lists/groups (e.g. Team A, Team B). Each group has editable names. Pick button with spin animation, shows result with confetti. History of picks. Settings: allow/prevent repeat picks, pick multiple at once. Import names from text (paste). Share pick result. Undo last pick. Persist groups and history with Codable + UserDefaults." },
    { title: "Decision wheel", prompt: "Build a decision wheel with custom categories. Main screen: animated spinning wheel divided into colored segments. Add/edit/remove options with custom labels and colors. Spin button triggers rotation animation, slowing to land on result. History of results. Multiple saved wheels (e.g. Lunch, Movie, Activity). Weight options so some are more likely. Sound on spin. Persist wheels with Codable + UserDefaults." },
    { title: "Coin flip", prompt: "Build a coin flip app with streaks. Main screen: large coin graphic with flip animation (3D rotation). Flip button and shake-to-flip gesture. Results: show Heads or Tails with running stats (total flips, heads count, tails count, percentage, current streak). History tab: list of last 50 flips with timestamps. Settings: choose coin style (4 options), toggle sound. Persist stats and history with Codable + UserDefaults." },
    { title: "Yes/No fortune", prompt: "Build a magic 8-ball fortune app. Main screen: 3D-style ball graphic with answer reveal animation. Ask a question (text field), shake or tap to get answer from expanded set (15+ responses across Positive, Neutral, Negative). History tab: list of past questions and answers with timestamps. Favorites: save interesting answers. Stats: most common response type. Custom answers editor. Persist with Codable + UserDefaults." },
  ],
  "UI states & patterns": [
    { title: "Profile placeholder", prompt: "Build a social profile with tabs. Main screen: header with avatar placeholder, name, handle, bio, stats row (Posts, Followers, Following counts). Below: segmented tabs (Posts, Likes, Media) each with placeholder lists. Edit profile sheet: editable name, bio, and link fields. Settings gear button in nav bar opening settings sheet. Follow/Unfollow button with state. Clean layout with proper spacing." },
    { title: "Onboarding flow", prompt: "Build a 5-screen onboarding with progress. Horizontal paging with page indicator dots and progress bar. Each page: illustration placeholder, title, subtitle. Page 3: permission prompt (notifications toggle). Page 4: preference picker (choose interests from a grid). Last page: Get Started and Skip buttons. Animated transitions between pages. Remember completion state in UserDefaults so onboarding only shows once." },
    { title: "About screen", prompt: "Build an about/info screen with sections. Main screen: app icon placeholder, app name, version, and tagline. Sections: What's New (list of features), Team (horizontal scroll of avatar+name cards), Links (Rate App, Privacy Policy, Terms — each opens alert). Footer: copyright and build number. Share app button. Animated header that collapses on scroll." },
    { title: "Empty state", prompt: "Build an app with contextual empty states. Main screen: tab bar with 3 tabs. Each tab shows a different empty state: Tab 1 (inbox icon + 'No messages yet' + 'Start a conversation' button), Tab 2 (search icon + 'No results' + search suggestion chips), Tab 3 (star icon + 'No favorites' + 'Browse items' button). Tapping CTA buttons shows sample content. Animated icon on each empty state." },
    { title: "Loading state", prompt: "Build an app demonstrating loading patterns. Main screen: 4 cards, each showing a different loading style. Card 1: spinner with label. Card 2: progress bar (0–100% over 3 seconds). Card 3: skeleton loading (gray shimmer rectangles that reveal content). Card 4: pull-to-refresh list. Reload button triggers all loading states simultaneously. Show success state after each loads." },
    { title: "Error state", prompt: "Build an app with error handling UI patterns. Main screen: 3 sections. Section 1: 'No Internet' state with retry button that succeeds on second try. Section 2: 'Server Error' with error code, message, and retry/report buttons. Section 3: 'Not Found' with search suggestion and home button. Each retry shows loading then success. Error animations (shake, fade). Toast notifications for recoverable errors." },
    { title: "Success screen", prompt: "Build a multi-step flow with success. 3-step form: Step 1 (info fields), Step 2 (confirmation with editable summary), Step 3 (animated success screen with checkmark animation, confetti, summary of what was submitted, and two buttons: Done and Share). Progress bar across all steps. Back navigation between steps. Animate step transitions. Reset and start over capability." },
    { title: "Detail screen", prompt: "Build a content detail screen with rich layout. Main screen: list of articles. Detail screen: hero image placeholder with parallax scroll effect, title, author with avatar, date, reading time estimate, body text with styled paragraphs. Action bar: like button with count, bookmark toggle, share button. Related articles section at bottom. Scroll-to-top button. Comments section with mock data." },
    { title: "Action sheet", prompt: "Build a photo actions demo. Main screen: grid of 6 photo placeholder cards. Tap card to show action sheet: View Full Screen, Edit (shows editor sheet with filters: Original/B&W/Sepia), Share, Delete (with confirmation alert). Full screen view: photo with dismiss button. Track action history in a log list accessible from toolbar. Each action shows toast confirmation." },
    { title: "Alert / confirm", prompt: "Build a settings screen with confirmation dialogs. Main screen: list of settings with destructive actions. 'Clear Cache' shows size and confirm dialog. 'Delete Account' shows multi-step confirmation (type DELETE to confirm). 'Log Out' shows alert with Cancel/Log Out. 'Reset Settings' shows alert listing what will be reset. Success/failure toasts after each action. Action history log." },
    { title: "Modal sheet", prompt: "Build an app with multiple sheet types. Main screen: 4 buttons. Button 1: half-sheet with detents (.medium, .large). Button 2: full sheet with form and Save/Cancel. Button 3: sheet with navigation stack inside (list → detail). Button 4: confirmation sheet with custom height. Proper sheet dismiss handling (warn on unsaved changes). Sheet presentation animation customization." },
    { title: "Full-screen cover", prompt: "Build an app with full-screen transitions. Main screen: content list. Tap item for full-screen cover with custom transition. Cover has: large content area, overlay controls (close button, share, like), swipe-down to dismiss gesture. Image viewer mode: pinch-to-zoom placeholder. Video player placeholder with play/pause overlay. Status bar hidden in full-screen mode. Smooth dismiss animation." },
  ],
  "Accessibility & system": [
    { title: "Haptic feedback", prompt: "Build a haptic playground. Main screen: grid of buttons, each triggering a different haptic type (light, medium, heavy, success, warning, error, selection change). Each button labeled with the haptic name. Toggle to enable/disable haptics. Pattern button: plays a sequence of haptics. Settings: intensity slider (maps to different generators). Log of triggered haptics with timestamps. Persist preference with UserDefaults." },
    { title: "Button with sound", prompt: "Build a soundboard app. Main screen: grid of 8 colored buttons, each playing a different system sound. Labels showing sound name. Volume slider. Favorites row: long-press button to add to favorites (shown at top). Settings: toggle vibration with sound, choose between 3 sound sets. Recently played list. Rapid-fire mode toggle (allow overlapping sounds). Persist favorites and settings with UserDefaults." },
    { title: "Dark mode", prompt: "Build a theme showcase app. Main screen: content demonstrating the theme — cards, lists, buttons, text styles, and icons. Settings: theme picker (Light, Dark, System, and 2 custom themes with unique accent colors). Live preview as theme changes with smooth animation. Proper use of semantic colors throughout. Theme affects all screens. Custom color palette display. Persist theme choice with UserDefaults." },
    { title: "Dynamic Type", prompt: "Build an accessibility showcase. Main screen: article-style content with headline, subheadline, body, caption, and footnote — all scaling with Dynamic Type. Accessibility inspector panel (toggle): shows current text size category, contrast ratio indicator. Custom font scaling for non-standard elements. Preview at different sizes (slider). Bold Text support. Reduce Motion support. Persist any preferences with UserDefaults." },
    { title: "Accessibility labels", prompt: "Build an accessible task app. Main screen: list of tasks with status icons, priority indicators, and action buttons — all with proper VoiceOver labels, hints, and traits. Custom accessibility actions (swipe actions announced). Accessibility container grouping. Image descriptions. Dynamic Type support. High contrast mode support. Rotor custom actions. Test panel showing all accessibility properties of selected element." },
    { title: "Share sheet", prompt: "Build a content sharing hub. Main screen: list of shareable items (quote cards, stats graphics, achievement badges). Each has a Share button that opens share sheet with formatted content. Share as: text, image (rendered card), or URL. Custom share message per item type. Share history tab: list of shared items with date and share method. Generate share card as rendered view. Persist share history with Codable + UserDefaults." },
    { title: "Copy to clipboard", prompt: "Build a text utility app with clipboard features. Main screen: tabs for different generators — Lorem Ipsum (configurable paragraphs), UUID Generator, Password Generator (length slider, toggles for uppercase/lowercase/numbers/symbols), Color Hex (random with preview). Each has Copy button with animated confirmation. Clipboard history tab: last 20 copied items with re-copy and delete. Persist history with Codable + UserDefaults." },
  ],
  "Placeholders & demos": [
    { title: "Step counter placeholder", prompt: "Build a fitness dashboard placeholder. Main screen: circular progress ring for steps (mock: 6,234 / 10,000). Below: stat cards in 2-column grid — Distance (3.2 mi), Calories (287), Active Minutes (42), Floors (8). Weekly bar chart placeholder showing steps per day. Goal settings sheet: daily step goal stepper. Motivational message based on progress. Animated progress ring on appear. History tab with mock weekly data." },
    { title: "Random quote (display)", prompt: "Build a quote app with categories. Main screen: featured quote in large typography with author and category tag. Swipe or Next/Previous buttons to navigate. Category filter: horizontal scroll chips (Motivation, Love, Success, Wisdom, Humor). Favorites tab: saved quotes list. Share button per quote (formatted text). 30+ quotes across categories. Daily quote notification placeholder. Animated quote transitions." },
    { title: "Affirmation app", prompt: "Build an affirmation app with scheduling. Main screen: beautiful full-screen affirmation with gradient background (cycles through 5 gradient themes). Swipe for next. Favorites tab: saved affirmations. Categories: Confidence, Gratitude, Growth, Peace. Settings: morning reminder time picker, choose category focus. 50+ affirmations. Calm animations (fade, scale). Streak counter (days opened). Persist with Codable + UserDefaults." },
    { title: "Minimal calendar", prompt: "Build a calendar with events. Main screen: month view grid with navigation (prev/next month, today button). Dots on dates with events. Tap date: list of events for that day below the calendar. Add event sheet: title, time, color picker, notes. Week view toggle. Event detail with edit/delete. Current day highlighted. Animated month transitions. Persist events with Codable + UserDefaults." },
    { title: "Weather placeholder", prompt: "Build a weather app with mock data. Main screen: current weather card (city, temp, condition icon, high/low). Below: hourly forecast horizontal scroll (next 12 hours). 5-day forecast list with day, icon, high/low. Details card: humidity, wind, UV index, feels like. City search sheet (pick from 5 preset cities, each with different mock weather). Background gradient changes with condition. Settings: toggle °F/°C." },
    { title: "Map placeholder", prompt: "Build a places app with map. Main screen: Map view with 5 annotated pins at different coordinates. Tap pin to show callout with place name and category. List view toggle: same places as a list with distance placeholder. Add place sheet: name, category picker, coordinate fields (or use map tap). Detail screen: map zoomed to pin, place info, and notes field. Filter pins by category. Persist places with Codable + UserDefaults." },
    { title: "Image picker placeholder", prompt: "Build a photo album app placeholder. Main screen: grid of photo placeholder cards (colored rectangles with numbers). Tap photo for full-screen view with share and delete buttons. Add photo button shows mock picker (3 options: Camera, Library, Color). Picking creates a new colored placeholder. Albums tab: create/manage albums, assign photos. Slideshow mode: auto-advance through photos. Persist with Codable + UserDefaults." },
    { title: "Camera placeholder", prompt: "Build a camera app placeholder. Main screen: viewfinder area (dark rectangle) with capture button, flash toggle, and camera flip button. Gallery strip at bottom showing last 3 captures (colored placeholders). Capture creates a new placeholder with timestamp. Gallery screen: grid of all captures with date sections. Detail view: full-screen with share, delete, and info (date, size placeholder). Filters preview strip (Original, B&W, Sepia, Vivid)." },
    { title: "Skeleton loading", prompt: "Build a social feed with skeleton loading. Main screen: on launch, show 5 skeleton rows (shimmer animation on gray rectangles for avatar, title, body, and image). After 2 seconds, animate to real content (posts with avatar initial, username, text, timestamp, and like/comment counts). Pull-to-refresh triggers skeleton again. Error state if refresh fails (mock toggle). Infinite scroll simulation (load 5 more with skeletons)." },
  ],
  "Design & visual": [
    { title: "Liquid Glass (iOS 26)", prompt: "Build a Liquid Glass style app with multiple screens. Main screen: frosted glass cards (using iOS 26 glassEffect if available, or blur + transparency fallback) showing dashboard stats. Navigation to detail screen with glass-morphism header. Settings sheet with glass-style grouped controls. Tab bar with glass background. Dynamic background that shifts color slowly. Proper light/dark adaptation. Smooth spring animations on all transitions." },
    { title: "Card with shadow", prompt: "Build a card-based UI showcase. Main screen: scrollable list of card styles — minimal (subtle shadow), elevated (pronounced shadow), outlined (border, no shadow), gradient (gradient background), image (photo placeholder with text overlay). Each card is tappable and expands with animation to detail view. Settings: toggle between light and dark card themes. Drag to reorder cards. Custom shadow color matches card accent. Persist order with UserDefaults." },
    { title: "Gradient background", prompt: "Build a gradient design tool. Main screen: full-screen gradient preview with two color pickers (start and end colors). Direction picker: horizontal, vertical, diagonal, radial. Presets row: 8 preset gradient combinations (Sunset, Ocean, Forest, etc.). Save gradient to collection. Collection tab: grid of saved gradients. Tap to apply. Export gradient as CSS code (share sheet). Animated gradient transitions when changing. Persist with Codable + UserDefaults." },
    { title: "Animated transition", prompt: "Build an animation showcase app. Main screen: list of 8 animation demos. Each navigates to a detail screen demonstrating: 1) Spring animation, 2) Matched geometry effect (hero transition), 3) Rotation with 3D perspective, 4) Path animation, 5) Staggered list animation, 6) Morphing shapes, 7) Particle-like effect (multiple animated circles), 8) Gesture-driven animation (drag with physics). Each demo has controls to adjust parameters (duration, damping, etc.)." },
  ],
  "Misc (display & interaction)": [
    { title: "Flashcard app", prompt: "Build a flashcard study app with decks. Main screen: list of decks with card count and mastery percentage. Tap deck to study: card view with 3D flip animation (question → answer). Buttons: Know It, Still Learning, Skip. Progress bar during study session. Results screen: cards mastered vs needs review. Edit deck: add/edit/delete cards. Create new deck sheet with name and color. Import cards from text. Persist with Codable + UserDefaults." },
    { title: "Word of the day", prompt: "Build a vocabulary builder. Main screen: today's word displayed large with pronunciation guide, part of speech, definition, and example sentence. Mark as learned button. Calendar tab: grid showing which days had words (green = learned, gray = skipped). Vocabulary list tab: all past words searchable, filterable by learned/not learned. Quiz mode: show definition, pick correct word from 4 options. 50+ words. Persist with Codable + UserDefaults." },
    { title: "Speed dial", prompt: "Build a speed dial with favorites and recents. Main screen: grid of large contact buttons (3×3) with avatar initials and names. Tap shows action sheet: Call, Message, Email (all show alerts in MVP). Edit mode: rearrange contacts, change grid size (3×3 or 4×4). Add contact sheet: name, phone, email, and color picker for avatar. Recents tab: list of tapped contacts with timestamps. Favorites section pinned at top. Persist with Codable + UserDefaults." },
  ],
};

const _flattened = Object.values(APP_IDEAS_MEDIUM_BY_CATEGORY).flat();
export const APP_IDEA_MEDIUM_PROMPTS: readonly string[] = _flattened.map((idea) => idea.prompt);
