import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

type PersistedChat = {
  projectId: string;
  updatedAt: number;
  messages: Array<{
    id: string;
    role: "user" | "assistant";
    content: string;
    editedFiles?: string[];
    usage?: { input_tokens: number; output_tokens: number };
    estimatedCostUsd?: number;
  }>;
};

const CHAT_DIR = join(process.cwd(), "data", "project-chats");

function chatFilePath(projectId: string): string {
  // projectId is generated by us; still, keep the path conservative.
  const safe = projectId.replace(/[^a-zA-Z0-9_-]/g, "");
  return join(CHAT_DIR, `${safe}.json`);
}

export async function getProjectChat(projectId: string): Promise<PersistedChat | null> {
  const file = chatFilePath(projectId);
  if (!existsSync(file)) return null;
  try {
    const raw = await readFile(file, "utf8");
    const parsed = JSON.parse(raw) as PersistedChat;
    if (!parsed || parsed.projectId !== projectId || !Array.isArray(parsed.messages)) return null;
    return parsed;
  } catch {
    return null;
  }
}

export async function setProjectChat(
  projectId: string,
  messages: PersistedChat["messages"]
): Promise<void> {
  await mkdir(CHAT_DIR, { recursive: true });
  const payload: PersistedChat = { projectId, updatedAt: Date.now(), messages };
  await writeFile(chatFilePath(projectId), JSON.stringify(payload), "utf8");
}

