name: VibeTreeCompanion
options:
  bundleIdPrefix: com.vibetree
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"

targets:
  VibeTreeCompanion:
    type: application
    platform: iOS
    sources:
      - path: VibeTreeCompanion
        excludes:
          - "**/*.plist"
      - path: Shared
    info:
      path: VibeTreeCompanion/Info.plist
      properties:
        CFBundleDisplayName: VibeTree
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibetree.companion
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: VibeTreeCompanion/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: BuildActivityExtension

  BuildActivityExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: BuildActivityExtension
        excludes:
          - "**/*.plist"
      - path: Shared
    info:
      path: BuildActivityExtension/Info.plist
      properties:
        CFBundleDisplayName: BuildActivity
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibetree.companion.buildactivity
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: BuildActivityExtension/Info.plist
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: BuildActivityExtension/BuildActivityExtension.entitlements
      properties: {}

schemes:
  VibeTreeCompanion:
    build:
      targets:
        VibeTreeCompanion: all
        BuildActivityExtension: all
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables: {}
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug
      targets:
        - VibeTreeCompanion
