name: VibTreeCompanion
options:
  bundleIdPrefix: com.vibetree
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"

targets:
  VibTreeCompanion:
    type: application
    platform: iOS
    sources:
      - path: VibTreeCompanion
        excludes:
          - "**/*.plist"
      - path: Shared
    info:
      path: VibTreeCompanion/Info.plist
      properties:
        CFBundleDisplayName: VibTree
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibetree.companion
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: VibTreeCompanion/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: BuildActivityExtension

  BuildActivityExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: BuildActivityExtension
        excludes:
          - "**/*.plist"
      - path: Shared
    info:
      path: BuildActivityExtension/Info.plist
      properties:
        CFBundleDisplayName: BuildActivity
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibetree.companion.buildactivity
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: BuildActivityExtension/Info.plist
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: BuildActivityExtension/BuildActivityExtension.entitlements
      properties: {}
