import { NextResponse } from "next/server";

/**
 * GET /api/projects/[id]/export
 * Returns the project's source as a downloadable file (e.g. Swift placeholder).
 * Mock: returns a minimal SwiftUI placeholder. Production would return the actual generated Swift or a ZIP of the project.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  if (!id) {
    return NextResponse.json({ error: "Project ID required" }, { status: 400 });
  }

  // Placeholder SwiftUI app so the download is valid. Replace with real generated source when available.
  const swiftContent = `// Vibetree export — ${id}
// Generated by Vibetree. Replace with your app's generated code when using the full build pipeline.

import SwiftUI

@main
struct VibetreeApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    var body: some View {
        VStack(spacing: 20) {
            Text("Hello from Vibetree")
                .font(.title)
            Text("Export your project from the editor to get the full generated Swift.")
                .font(.caption)
                .multilineTextAlignment(.center)
                .foregroundStyle(.secondary)
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
`;

  return new NextResponse(swiftContent, {
    status: 200,
    headers: {
      "Content-Type": "text/x-swift",
      "Content-Disposition": `attachment; filename="Vibetree-${id.slice(0, 20)}.swift"`,
    },
  });
}
