import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CreditsProvider } from "@/contexts/CreditsContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontVariableClasses = [geistSans.variable, geistMono.variable].join(" ");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariableClasses} suppressHydrationWarning>
      <body className="antialiased">
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=document.documentElement;var th=localStorage.getItem('vibetree-theme');if(th){t.setAttribute('data-theme',th);}})();`,
          }}
        />
        <CreditsProvider>
          {children}
        </CreditsProvider>
      </body>
    </html>
  );
}
