import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Plus_Jakarta_Sans, Outfit, DM_Sans, Playfair_Display } from "next/font/google";
import { CreditsProvider } from "@/contexts/CreditsContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

/** All font variables must be on the document so [data-font] can switch --font-sans */
const fontVariableClasses = [
  geistSans.variable,
  geistMono.variable,
  inter.variable,
  plusJakartaSans.variable,
  outfit.variable,
  dmSans.variable,
  playfairDisplay.variable,
].join(" ");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariableClasses} suppressHydrationWarning>
      <body className="antialiased">
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=document.documentElement;var th=localStorage.getItem('vibetree-theme');if(th){t.setAttribute('data-theme',th);}var f=localStorage.getItem('vibetree-font');if(f){t.setAttribute('data-font',f);}})();`,
          }}
        />
        <CreditsProvider>
          {children}
        </CreditsProvider>
      </body>
    </html>
  );
}
