import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";
import { CreditsProvider } from "@/contexts/CreditsContext";
import { DevActivityWidget } from "@/components/dev/DevActivityWidget";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontVariableClasses = [geistSans.variable, geistMono.variable].join(" ");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariableClasses} data-theme="emerald" suppressHydrationWarning>
      <body className="antialiased">
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=document.documentElement;var th=localStorage.getItem('vibetree-theme')||'emerald';t.setAttribute('data-theme',th);})();`,
          }}
        />
        <AuthProvider>
          <CreditsProvider>
            {children}
            {process.env.NODE_ENV === "development" && <DevActivityWidget />}
          </CreditsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
