/**
 * GET /api/cron/daily
 * Daily cron job. Call from Vercel Cron or external scheduler.
 * Requires CRON_SECRET in Authorization header or query.
 */
import { NextResponse } from "next/server";
import { getAdminDb } from "@/lib/firebaseAdmin";
import { sendDigestEmail } from "@/lib/email";

function verifyCronSecret(request: Request): boolean {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  const auth = request.headers.get("authorization");
  if (auth?.startsWith("Bearer ")) return auth.slice(7) === secret;
  const url = new URL(request.url);
  return url.searchParams.get("secret") === secret;
}

export async function GET(request: Request) {
  if (!verifyCronSecret(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const results: Record<string, unknown> = { ok: true, at: new Date().toISOString() };

  try {
    const db = getAdminDb();
    const waitlistSnap = await db.collection("waitlist").count().get();
    const projectsSnap = await db.collection("projects").count().get();
    results.waitlistCount = waitlistSnap.data().count;
    results.projectsCount = projectsSnap.data().count;
  } catch (e) {
    results.firestoreError = e instanceof Error ? e.message : String(e);
  }

  const digestEmail = process.env.CRON_DIGEST_EMAIL;
  if (digestEmail && results.waitlistCount !== undefined) {
    const sent = await sendDigestEmail({
      to: digestEmail,
      subject: "VibeTree daily digest",
      body: `Waitlist: ${results.waitlistCount}\nProjects: ${results.projectsCount ?? "N/A"}\n\nGenerated by /api/cron/daily`,
    });
    if (!sent.ok) results.digestError = "Failed to send";
  }

  return NextResponse.json(results);
}
